# 중급반 1주차 
* [Sentiment Analysis on Movie Reviews | Kaggle](https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews) 
* 텍스트 데이터를 처리하는 법 배우기
* 새로운 인공지능 알고리즘인 Regression Model 사용해보기

### 중급반 개요

* 난이도가 있고 다양한 부분을 다룰 것
* 기본적인 노하우를 많이 알려줄 것임

* 가능한 스스로 많이 하고 성능을 올릴 수 있도록 할것임
* 컴페티션 위주로 진행하고 초반부 2주가 텍스트처리
* 텍스트 처리에서 감정분석으로 많이 시작함 => 가장 쉽고 보편적인 내용을 배우고 동일하게 여러 곳에 적용할 수 있음

#### 영문 데이터
* 오늘 하는 것은 영어 데이터를 위주로 할 것이며 영어 쪽에 툴이 잘 되어 있음
* 영어에서 쓸 수 있는 툴 중에 한국에서 쓸 수 있는 게 제한 적임
* 영어 툴 중에 한국어에 적용할 수 있는 것들 위주로 가져올 것임, 한국어에 거의 동일하게 적용이 가능하다.

#### 데이터용량
* 후반 부에는 용량이 좀 큰 데이터를 사용한다.
* 로그를 많이 쌓는 곳에서는 하루에 텍스트가 1T정도 쌓이기도 한다.
* 우리에게 적합한 메모리효율적으로 사용할 수 있는지에 대한 노하우를 배움

#### 입문반과의 차이점
입문반과 가장 큰 차이점은 분석을 많이해서 가지고 있는 아이디어나 전문지식을 통해서 어떻게 분석을 하고 그 결과를 어떻게 모델에 넣을 것인가
엑셀로 디테일하게 분석하고 어떻게 집어 넣을 수 있는지 배우는 게 전반적인 코스


머신러닝의 카테고리가 크게 3가지가 있다.
* 지도학습과 비지도학습의 차이는 레이블이 있느냐 없느냐의 차이
* 이 강의에서 주로 하는 것은 지도학습이 주를 이룸
- Supervised Learning -> X, y
    - 굉장히 핫하지만 데이터셋이 많지 않다.
    - 막강한 알고리즘이 많아 대세가 될 것임
    - tree base 알고리즘 
        - DT
        - RF
        - GBM
    - regression
        - 딥러닝
        - *로지스틱 리그레션 <== 오늘 수업에서 사용할 것*
        - SVM
    - 기타
        - KNN
        - 나이브베이즈
    
- Unsupervised Learning -> X
    - 편하고 활용가치가 높다.
    - 알고리즘쪽으로 발전가능성이 높지 않다.
    - 추천엔진
- Reinforcement Learning
    - 알파고
    - 게임을 승리하기 위해 어떤 과정을 거치느냐, 지도학습과 비지도학습과 완전 다른 것
    - 가장 쓸데없음, 조건이 너무 까다롭다. 
    
    
입문 3주차 때 리니어/로지스틱 리그레션을 사용
리그레션이 정수형의 높고 낮음을 나타냄
X축으로 방의 갯수로 집값을 예측한다는 예를 들어보면 그래프에 맞는 값을 넣으면 집 값을 맞출 수 있을 것이다.

랜덤하게 아무선이나 긋고 y와 정답 레이블과 진짜 결과값을 예측하고 차이를 보정해 나간다. 
차이가 없어질 때까지 간다.

리그레션 모델 - 0에 근접해 가도록 만든다.
=> 그라디언트 디센트

In [1]:
import pandas as pd

# Load Dataset

In [2]:
ls data/

baseline-script.csv   test.tsv              train.tsv.zip
result.csv            test.tsv.zip          vocabulary.csv
sampleSubmission.csv  train.tsv

In [3]:
train = pd.read_csv("data/train.tsv", sep="\t", index_col="PhraseId")
print(train.shape)
train.head()

(156060, 3)

,SentenceId,Phrase,Sentiment
PhraseId,,,
1,1,A series of escapades demonstrating the adage ...,1
2,1,A series of escapades demonstrating the adage ...,2
3,1,A series,2
4,1,A,2
5,1,series,2

In [4]:
test = pd.read_csv("data/test.tsv", sep="\t", index_col="PhraseId")
print(test.shape)
test.head()

(66292, 2)

          SentenceId                                             Phrase
PhraseId
156061          8545  An intermittently pleasing but mostly routine ...
156062          8545  An intermittently pleasing but mostly routine ...
156063          8545                                                 An
156064          8545  intermittently pleasing but mostly routine effort
156065          8545         intermittently pleasing but mostly routine

In [5]:
train.loc[1]["Phrase"]

'A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .'

이 문장을 분석해서 써야함, 이런 문장을 비정형 데이터라 함, 비정형 데이터를 정형화 하는데 시간이 오래 걸림
이런 댓글을 다루는 게 더 좋음
평점이 낮은 문장임 여기에서 포지티브 네거티브한 문장이 있을 것임

"나는 | 딥러닝이 | 좋습니다."
1 | 1 | 1 | 0000

one hot encoding = vecterize phrases

자연어 처리를 어떻게 하는지에 대한 툴을 알면 이것을 쉽게 해결한다.

* [Amazon Mechanical Turk - Welcome](https://www.mturk.com/mturk/welcome)

* 데이터를 분석하기 좋게 쪼갠다.
* 맨 앞에 있는 게 진짜 리뷰, 전체 문장 중 어느 부분이 긍정적이고 부정적인지를 알 수 있다.

# Preprocssing

In [6]:
train["Phrase(origin)"] = train["Phrase"].copy()

print(train.shape)
train[["Phrase", "Phrase(origin)"]].head()

(156060, 4)

,Phrase,Phrase(origin)
PhraseId,,
1,A series of escapades demonstrating the adage ...,A series of escapades demonstrating the adage ...
2,A series of escapades demonstrating the adage ...,A series of escapades demonstrating the adage ...
3,A series,A series
4,A,A
5,series,series

In [7]:
test["Phrase(origin)"] = test["Phrase"].copy()

print(test.shape)
test[["Phrase", "Phrase(origin)"]].head()

(66292, 3)

,Phrase,Phrase(origin)
PhraseId,,
156061,An intermittently pleasing but mostly routine ...,An intermittently pleasing but mostly routine ...
156062,An intermittently pleasing but mostly routine ...,An intermittently pleasing but mostly routine ...
156063,An,An
156064,intermittently pleasing but mostly routine effort,intermittently pleasing but mostly routine effort
156065,intermittently pleasing but mostly routine,intermittently pleasing but mostly routine

# Clean Text

In [8]:
# phrase = "ca n't recommend it"

def clean_text(phrase):
    phrase =  phrase.replace("doesn't", "does not ")
    phrase =  phrase.replace("ca n't", "can not ")
    phrase =  phrase.replace("n't", " not ")
    
    return phrase

train["Phrase"] = train["Phrase"].apply(clean_text)
train[["Phrase", "Phrase(origin)"]].head()

,Phrase,Phrase(origin)
PhraseId,,
1,A series of escapades demonstrating the adage ...,A series of escapades demonstrating the adage ...
2,A series of escapades demonstrating the adage ...,A series of escapades demonstrating the adage ...
3,A series,A series
4,A,A
5,series,series

In [9]:
test["Phrase"] = test["Phrase"].apply(clean_text)
test[["Phrase", "Phrase(origin)"]].head()

,Phrase,Phrase(origin)
PhraseId,,
156061,An intermittently pleasing but mostly routine ...,An intermittently pleasing but mostly routine ...
156062,An intermittently pleasing but mostly routine ...,An intermittently pleasing but mostly routine ...
156063,An,An
156064,intermittently pleasing but mostly routine effort,intermittently pleasing but mostly routine effort
156065,intermittently pleasing but mostly routine,intermittently pleasing but mostly routine

In [10]:
train[train["Phrase"].str.contains("ca n't recommend")]

Empty DataFrame
Columns: [SentenceId, Phrase, Sentiment, Phrase(origin)]
Index: []

In [11]:
# one hot encoding = vecterize phrases

[sklearn.feature_extraction.text.CountVectorizer — scikit-learn 0.19.0 documentation](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)

### ngram_range(1, 2)  
2개를 묶어주면 2 gram
3개를 묶어주면 trigram
나는 | 딥러닝이 | 좋습니다.
<pre>
나는 
딥러닝이
좋습니다.

나는 딥러닝이
딥러닝이 좋습니다.
</pre>
* 단어 앞뒤를 묶어서 넣는다.

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
# binary = True/False
# lowercase = True/False
# ngram_range(1, 2) 
# stop_word=None a나 the가 지금은 빠져있는 데 넣을 수도 있음
# 단어를 천개만 넣었다가 만개로 늘림 stunning이 나와서

vectorizer = CountVectorizer(max_features=10000, ngram_range=(1,2))
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=10000, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [13]:
vectorizer.fit(train["Phrase"])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=10000, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [14]:
X_train = vectorizer.transform(train["Phrase"])
X_train

<156060x10000 sparse matrix of type '<class 'numpy.int64'>'
	with 1152072 stored elements in Compressed Sparse Row format>

* 특수기호를 처리해야 점수가 올라간다. 이에 대한 노가다가 필요하다.
* 특수기호가 몇 개 이상있으면 긍정인지 부정인지
* 띄어쓰기 + 특수기호 제거로 count_vertorize

In [15]:
columns = vectorizer.get_feature_names()
pd.DataFrame(X_train[:100].toarray(), columns=columns).head()

,000,10,10 minutes,10 year,100,101,11,12,12 year,13,...,your watch,yourself,youth,youthful,zany,zeal,zero,zhang,zombie,zone
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
X_test = vectorizer.transform(train["Phrase"])
X_test

<156060x10000 sparse matrix of type '<class 'numpy.int64'>'
	with 1152072 stored elements in Compressed Sparse Row format>

In [17]:
y_train = train["Sentiment"]

print(y_train.shape)
y_train.head()

(156060,)

PhraseId
1    1
2    2
3    2
4    2
5    2
Name: Sentiment, dtype: int64

# Score
* 데이터의 양이 많아 RF의 속도가 굉장히 느리다.
* 로우 10만개 컬럼 천개, 엄청 오래 걸리고 점수도 좋지 않다.
* 보통은 RF가 잘나오지만 무비리뷰에 잘나오는 리니어 모델을 사용

In [18]:
from sklearn.linear_model import SGDClassifier

model = SGDClassifier(random_state=37)
model

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=5, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=37, shuffle=True,
       tol=None, verbose=0, warm_start=False)

In [19]:
# # from sklearn.cross_validation import cross_val_score # 아나콘다 환경 일 때
# from sklearn.model_selection import cross_val_score

# score = cross_val_score(model, X_train, y_train, cv=5).mean()

# print("Score = {0:.5f}".format(score))
# # 오늘 목표는 0.60까지 
# Score = 0.55597

In [20]:
# from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import cross_val_predict

y_predict = cross_val_predict(model, X_train, y_train, cv=5)

print(y_predict.shape)
y_predict[0:10]

(156060,)

array([1, 2, 2, 2, 2, 2, 2, 3, 2, 3])

In [21]:
# 시간 될 때 metrics 자세히 볼 것
from sklearn.metrics import accuracy_score

score = accuracy_score(y_train, y_predict)
print("Score = {0:.5f}".format(score))

Score = 0.57621

In [22]:
import numpy as np

result = train.copy()
result["Sentiment(predict)"] = y_predict
result["Difference(Phrase)"] = np.abs(y_train - y_predict)

# 많이 틀린것으로 정렬
# result.sort_values()

print(result.shape)
result.head()
# Difference 가 0인 것은 고칠 필요가 없다.
# Difference 가 높은 것부터 고쳐나가는게 더 도움이 된다.
# train 데이터 15만개를 모두 볼 수가 없다. 그래서 고치면 많이 올라가는 것을 고친다.

# 묶여있는 센텐스ID 전체의 차이를 구한다. 하나의 센텐스에 여러개의 Phase가 있기 때문에 차이가 높은 순으로 정렬한다.

(156060, 6)

,SentenceId,Phrase,Sentiment,Phrase(origin),Sentiment(predict),Difference(Phrase)
PhraseId,,,,,,
1,1,A series of escapades demonstrating the adage ...,1,A series of escapades demonstrating the adage ...,1,0
2,1,A series of escapades demonstrating the adage ...,2,A series of escapades demonstrating the adage ...,2,0
3,1,A series,2,A series,2,0
4,1,A,2,A,2,0
5,1,series,2,series,2,0

In [23]:
# 센텐스 마다의 평점
# 쪼갠 것도 점수에 대한 평점을 기록함 미케니컬 텅크를 사용해서
sentiment = result.groupby("SentenceId")["Difference(Phrase)"].mean()

print(sentiment.shape)

sentiment.head()

(8529,)

SentenceId
1    0.222222
2    0.555556
3    0.314286
4    0.675000
5    0.800000
Name: Difference(Phrase), dtype: float64

In [24]:
def find_sentiment(sentence_id):
    return sentiment.loc[sentence_id]

result["Difference(Sentence)"] = result["SentenceId"].apply(find_sentiment)
result = result.sort_values(by="Difference(Sentence)", ascending=False)

print(result.shape)
result.head()

(156060, 7)

,SentenceId,Phrase,Sentiment,Phrase(origin),Sentiment(predict),Difference(Phrase),Difference(Sentence)
PhraseId,,,,,,,
82704,4270,biggest disappointments,0,biggest disappointments,2,2,2.625
82703,4270,the biggest disappointments,1,the biggest disappointments,2,1,2.625
82702,4270,the biggest disappointments of the year,1,the biggest disappointments of the year,2,1,2.625
82701,4270,of the biggest disappointments of the year,0,of the biggest disappointments of the year,2,2,2.625
82700,4270,one of the biggest disappointments of the year,1,one of the biggest disappointments of the year,4,3,2.625

In [25]:
result[0:1000].to_csv("data/result.csv")

In [26]:
vocabulary = vectorizer.get_feature_names()
pd.DataFrame(vocabulary, columns=["word"]).to_csv("data/vocabulary.csv")

In [27]:
# stunning 이 포함 된 단어만 보여줌
result[result["Phrase"].str.contains("stunning")]

,SentenceId,Phrase,Sentiment,Phrase(origin),Sentiment(predict),Difference(Phrase),Difference(Sentence)
PhraseId,,,,,,,
47004,2290,combined with stunning animation,4,combined with stunning animation,2,2,1.125000
47005,2290,with stunning animation,4,with stunning animation,2,2,1.125000
47006,2290,stunning animation,4,stunning animation,2,2,1.125000
47003,2290,combined with stunning animation .,4,combined with stunning animation .,2,2,1.125000
46999,2290,A truly wonderful tale combined with stunning ...,4,A truly wonderful tale combined with stunning ...,4,0,1.125000
104913,5542,Some stunning visuals,4,Some stunning visuals,2,2,1.111111
104914,5542,stunning visuals,3,stunning visuals,4,1,1.111111
104912,5542,Some stunning visuals -- and some staggeringly...,2,Some stunning visuals -- and some staggeringly...,4,2,1.111111
120078,6422,stunning film,4,stunning film,2,2,0.888889
120077,6422,a stunning film,3,a stunning film,2,1,0.888889
120074,6422,"is a stunning film , a one-of-a-kind tour de f...",4,"is a stunning film , a one-of-a-kind tour de f...",4,0,0.888889
120073,6422,"is a stunning film , a one-of-a-kind tour de f...",4,"is a stunning film , a one-of-a-kind tour de f...",4,0,0.888889
120072,6422,"This is a stunning film , a one-of-a-kind tour...",4,"This is a stunning film , a one-of-a-kind tour...",4,0,0.888889
120076,6422,"a stunning film ,",4,"a stunning film ,",2,2,0.888889
120075,6422,"a stunning film , a one-of-a-kind tour de force",4,"a stunning film , a one-of-a-kind tour de force",4,0,0.888889
141588,7682,from a stunningly unoriginal premise,1,from a stunningly unoriginal premise,2,1,0.818182
141589,7682,a stunningly unoriginal premise,1,a stunningly unoriginal premise,2,1,0.818182
141590,7682,stunningly unoriginal premise,2,stunningly unoriginal premise,2,0,0.818182
141591,7682,stunningly unoriginal,0,stunningly unoriginal,2,2,0.818182
141586,7682,that proceeds from a stunningly unoriginal pre...,1,that proceeds from a stunningly unoriginal pre...,2,1,0.818182
141582,7682,"A sloppy , amusing comedy that proceeds from a...",1,"A sloppy , amusing comedy that proceeds from a...",3,2,0.818182
141581,7682,"A sloppy , amusing comedy that proceeds from a...",3,"A sloppy , amusing comedy that proceeds from a...",3,0,0.818182
77878,4006,"redone for horses , with fewer deliberate laug...",0,"redone for horses , with fewer deliberate laug...",1,1,0.742857
77880,4006,"for horses , with fewer deliberate laughs , mo...",2,"for horses , with fewer deliberate laughs , mo...",1,1,0.742857
77881,4006,"horses , with fewer deliberate laughs , more i...",2,"horses , with fewer deliberate laughs , more i...",1,1,0.742857
77884,4006,"with fewer deliberate laughs , more inadverten...",1,"with fewer deliberate laughs , more inadverten...",1,0,0.742857
77885,4006,"fewer deliberate laughs , more inadvertent one...",1,"fewer deliberate laughs , more inadvertent one...",1,0,0.742857
77886,4006,"fewer deliberate laughs , more inadvertent one...",1,"fewer deliberate laughs , more inadvertent one...",1,0,0.742857
77889,4006,", more inadvertent ones and stunningly trite",1,", more inadvertent ones and stunningly trite",2,1,0.742857
77890,4006,more inadvertent ones and stunningly trite,2,more inadvertent ones and stunningly trite,2,0,0.742857
...,...,...,...,...,...,...,...
102636,5406,This is a visually stunning rumination on love...,3,This is a visually stunning rumination on love...,4,1,0.411765
102638,5406,"is a visually stunning rumination on love , me...",4,"is a visually stunning rumination on love , me...",4,0,0.411765
102639,5406,"a visually stunning rumination on love , memor...",3,"a visually stunning rumination on love , memor...",4,1,0.411765
102640,5406,a visually stunning rumination,3,a visually stunning rumination,4,1,0.411765
102641,5406,visually stunning rumination,4,visually stunning rumination,4,0,0.411765
102642,5406,visually stunning,4,visually stunning,4,0,0.411765
115113,6132,Both a grand tour through 300 hundred years of...,4,Both a grand tour through 300 hundred years of...,4,0,0.411765
115114,6132,Both a grand tour through 300 hundred years of...,4,Both a grand tour through 300 hundred years of...,4,0,0.411765
115115,6132,a grand tour through 300 hundred years of Russ...,4,a grand tour through 300 hundred years of Russ...,4,0,0.411765
115118,6132,through 300 hundred years of Russian cultural ...,3,through 300 hundred years of Russian cultural ...,4,1,0.411765
115119,6132,300 hundred years of Russian cultural identity...,3,300 hundred years of Russian cultural identity...,4,1,0.411765
115122,6132,of Russian cultural identity and a stunning te...,3,of Russian cultural identity and a stunning te...,4,1,0.411765
115123,6132,Russian cultural identity and a stunning techn...,4,Russian cultural identity and a stunning techn...,4,0,0.411765
115127,6132,a stunning technical achievement,4,a stunning technical achievement,4,0,0.411765
115128,6132,stunning technical achievement,4,stunning technical achievement,4,0,0.411765
79706,4104,which is best for the stunning star turn by Dj...,4,which is best for the stunning star turn by Dj...,4,0,0.304348
79712,4104,stunning star turn,4,stunning star turn,4,0,0.304348
79711,4104,the stunning star turn,3,the stunning star turn,4,1,0.304348
79710,4104,the stunning star turn by Djeinaba Diop Gai,4,the stunning star turn by Djeinaba Diop Gai,4,0,0.304348
79709,4104,for the stunning star turn by Djeinaba Diop Gai,4,for the stunning star turn by Djeinaba Diop Gai,2,2,0.304348
79708,4104,best for the stunning star turn by Djeinaba Di...,4,best for the stunning star turn by Djeinaba Di...,4,0,0.304348
79707,4104,is best for the stunning star turn by Djeinaba...,3,is best for the stunning star turn by Djeinaba...,4,1,0.304348
79697,4104,Wobbly Senegalese updating of `` Carmen '' whi...,2,Wobbly Senegalese updating of `` Carmen '' whi...,3,1,0.304348
79698,4104,Senegalese updating of `` Carmen '' which is b...,3,Senegalese updating of `` Carmen '' which is b...,3,0,0.304348
155596,8516,"creates a stunning , Taxi Driver-esque portray...",3,"creates a stunning , Taxi Driver-esque portray...",4,1,0.157895
155595,8516,"creates a stunning , Taxi Driver-esque portray...",4,"creates a stunning , Taxi Driver-esque portray...",4,0,0.157895
155598,8516,"a stunning , Taxi Driver-esque portrayal",4,"a stunning , Taxi Driver-esque portrayal",4,0,0.157895
155597,8516,"a stunning , Taxi Driver-esque portrayal of a ...",4,"a stunning , Taxi Driver-esque portrayal of a ...",4,0,0.157895
155599,8516,"stunning , Taxi Driver-esque portrayal",4,"stunning , Taxi Driver-esque portrayal",4,0,0.157895
155594,8516,"Williams creates a stunning , Taxi Driver-esqu...",4,"Williams creates a stunning , Taxi Driver-esqu...",4,0,0.157895

In [28]:
result[result["Phrase"].str.contains("ca n't recommend")]

Empty DataFrame
Columns: [SentenceId, Phrase, Sentiment, Phrase(origin), Sentiment(predict), Difference(Phrase), Difference(Sentence)]
Index: []

In [29]:
model.fit(X_train, y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=5, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=37, shuffle=True,
       tol=None, verbose=0, warm_start=False)

In [30]:
predictions = model.predict(X_test)

print(predictions.shape)
predictions[0:10]

(156060,)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Score

In [31]:
submission = pd.read_csv("data/sampleSubmission.csv", index_col="PhraseId")

print(submission.shape)
submission.head()

(66292, 1)

          Sentiment
PhraseId
156061            2
156062            2
156063            2
156064            2
156065            2

In [32]:
submission.to_csv("data/baseline-script.csv")

*  문장을 단어화 시키고 중요한 단어와 중요하지 않은 단어가 있을 것임
* "나는 | 딥러닝이 | 좋습니다."
x1 = 나는 x2 = 딥러닝이 x3=좋습니다.
단어를 만들어 넣으면 내부 알고리즘으로 어떻게 좋은지에 따라 숫자에 가중치를 넣어 준다.
단어를 스스로 찾게하지 않으면 인공지능이 필요 없어짐

데이터를 잘 넣어주는 게 가장 중요하다.
그리고 인공지능이 이 단어가 긍정적인지 부정적인지 판단해 주는 게 더 중요하다.
=> 이렇게 개선한다.

15만개 데이터 하나하나 예측을 해서 예측값과 실제값을 비교할 것이다.
그 이전에 하나하나의 로우에서 센티멘트가 긍정적인데 부정적으로 부정적인 것을 긍정적인것을 분석했구나를 일일하게 확인한다.

모델을 개선할 때 타이타닉할 때도 실수했던 것이 생존을 기준으로 본다면 죽은 사람을 맞추는 것보다 산 사람을 살리는 방향으로 개선하는 게 좋다.
정답은 사는 건데 죽었다고 하는 것을 고치고 사는 건데 죽었다고 하는 것을 고친다.

긍정<->부정인게 잘못 된 예측을 고친다.